In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
datapaises = {
    'pais': ['España', 'Francia', 'Italia', 'Alemania', 'Reino Unido'],
    'capital': ['Madrid', 'París', 'Roma', 'Berlín', 'Londres'],
    'superficie': [505990, 643801, 301340, 357022, 242495],
}

In [3]:
df = pd.DataFrame(datapaises)
df

          pais  capital  superficie
0       España   Madrid      505990
1      Francia    París      643801
2       Italia     Roma      301340
3     Alemania   Berlín      357022
4  Reino Unido  Londres      242495

In [4]:
df[2:5]

          pais  capital  superficie
2       Italia     Roma      301340
3     Alemania   Berlín      357022
4  Reino Unido  Londres      242495

In [8]:
df.index = ['ESP', 'FRA', 'ITA', 'DEU', 'UK']
df = df.reset_index()
df

  index         pais  capital  superficie
0   ESP       España   Madrid      505990
1   FRA      Francia    París      643801
2   ITA       Italia     Roma      301340
3   DEU     Alemania   Berlín      357022
4    UK  Reino Unido  Londres      242495