In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
df = pd.read_csv('data/influencers.csv', index_col='id')
df.head(10)

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,ALICANTE,sofiasantos,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,MADRID,adrianramos,389.0,258
183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,ELCHE,dianapardo,12.0,129
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,ELCHE,dianapardo,12.0,129
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,ALICANTE,sofiasantos,982.0,1822

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 183721 to 183747
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  27 non-null     str
 1   favorites  26 non-null     float64
 2   retweets   26 non-null     float64
 3   mentions   26 non-null     float64
 4   country    27 non-null     str
 5   user       27 non-null     str
 6   followers  26 non-null     float64
 7   followees  27 non-null     int64
dtypes: float64(4), int64(1), str(3)
memory usage: 1.8 KB

In [14]:
df_filtrado = df.fillna({'retweets': 0, 'mentions':-1})
df_filtrado.head(10)

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,ALICANTE,sofiasantos,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,MADRID,adrianramos,389.0,258
183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,ELCHE,dianapardo,12.0,129
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,ELCHE,dianapardo,12.0,129
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,ALICANTE,sofiasantos,982.0,1822

In [16]:
df_filtrado.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 183721 to 183747
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_text  27 non-null     str
 1   favorites  26 non-null     float64
 2   retweets   27 non-null     float64
 3   mentions   27 non-null     float64
 4   country    27 non-null     str
 5   user       27 non-null     str
 6   followers  26 non-null     float64
 7   followees  27 non-null     int64
dtypes: float64(4), int64(1), str(3)
memory usage: 1.8 KB

In [17]:
df[(df['favorites'] > 400) & (df['mentions'] > 20)]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183744,Thanks man!,430.0,143.0,28.0,ALICANTE,cristianoronaldo,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,ALICANTE,cristianoronaldo,82.0,351
183746,BORED AF,488.0,28.0,27.0,ELCHE,danicarvajal,21.0,2721